# Generated by Django 6.1.1 on 2026-09-26 11:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("username", models.CharField(editable=False, max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("is_superuser", models.BooleanField(default=False)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "users",
                "ordering": ("-created_at", "-id"),
                "abstract": False,
                "default_permissions": (),
            },
        ),
    ]
