# Generated by Django 6.1.1 on 2026-09-27 10:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_userrole"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("session_id", models.UUIDField(editable=False)),
                ("secret_hash", models.CharField(max_length=64, unique=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "session_grants",
                "ordering": ("-issued_at", "-id"),
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=["user", "expires_at"],
                        name="session_grant_active_user_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("expires_at__gt", models.F("issued_at"))),
                        name="session_grant_expiry_after_issue",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("revoked_at__isnull", True),
                            ("revoked_at__gte", models.F("issued_at")),
                            _connector="OR",
                        ),
                        name="session_grant_revocation_after_issue",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("session_id",),
                        name="session_grant_one_unrevoked_per_session",
                    ),
                ],
            },
        ),
    ]
