[project]
name = "app-name"
version = "0.1.0"
description = "..."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "django>=6.1.1",
  "djangorestframework>=3.18.1",
  "drf-spectacular>=0.30.0",
  "loguru>=0.7.3",
  "pydantic-settings>=2.15.0",
]

[dependency-groups]
dev = [
  "django-stubs>=6.1.1",
  "django-stubs-ext>=6.1.1",
  "djangorestframework-stubs>=3.18.1",
  "pyright>=1.1.414",
  "pytest>=9.1.1",
  "pytest-django>=4.14.0",
  "ruff>=0.16.8",
]

[tool.pyright]
pythonVersion = "3.14"
typeCheckingMode = "standard"
venvPath = "."
venv = ".venv"

[tool.ruff]
line-length = 100
cache-dir = ".cache/ruff"
fix = true

[tool.ruff.lint.extend-per-file-ignores]
"**/migrations/*.py" = ["RUF012"]

[tool.pytest.ini_options]
pythonpath = "."
addopts = "--maxfail=1 --tb=line --no-header"
console_output_style = "times"
cache_dir = ".cache/pytest"
DJANGO_SETTINGS_MODULE = "conf.settings"
