# Generated by Django 6.1.1 on 2026-09-26 11:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "ADMIN"), ("normal", "NORMAL")],
                        editable=False,
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_roles",
                "ordering": ("-created_at", "-id"),
                "abstract": False,
                "default_permissions": (),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("role__in", ["admin", "normal"])),
                        name="user_roles_role_is_valid",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("user", "role"),
                        name="user_roles_active_assignment_is_unique",
                    ),
                ],
            },
        ),
    ]
